In [ ]:
# Multiple Linear Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/Refactor_Notes/ML_Models_Python_Sessions/Data_files/50_Startups.csv')

In [ ]:
dataset.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
## Selecting our target variable(dependent variable) and keeping the features aside (independent variable)
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, 4]

In [ ]:
X.head(5)

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [ ]:
y.head(5)

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [ ]:
## Refer the slides

In [ ]:
#Convert the column into categorical columns
## https://www.learndatasci.com/glossary/dummy-variable-trap/

## Refer the link for dummy variable trap
states=pd.get_dummies(X['State'], drop_first=True)

states.head(5)

   Florida  New York
0        0         1
1        0         0
2        1         0
3        0         1
4        1         0

In [ ]:
X.head(5)

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [ ]:

# Drop the state coulmn
X=X.drop('State',axis=1)

X.head(3)

   R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54

In [ ]:
# concat the dummy variables
X=pd.concat([X,states],axis=1)

In [ ]:
X.head(5)

   R&D Spend  Administration  Marketing Spend  Florida  New York
0  165349.20       136897.80        471784.10        0         1
1  162597.70       151377.59        443898.53        0         0
2  153441.51       101145.55        407934.54        1         0
3  144372.41       118671.85        383199.62        0         1
4  142107.34        91391.77        366168.42        1         0

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train.head(2)

    R&D Spend  Administration  Marketing Spend  Florida  New York
33   55493.95       103057.49        214634.81        1         0
35   46014.02        85047.44        205517.64        0         1

In [ ]:
X_test.head(2)

    R&D Spend  Administration  Marketing Spend  Florida  New York
28   66051.52       182645.56        118148.20        1         0
11  100671.96        91790.61        249744.55        0         0

In [ ]:
y_train.head(2)

33    96778.92
35    96479.51
Name: Profit, dtype: float64

In [ ]:
y_test.head(2)

28    103282.38
11    144259.40
Name: Profit, dtype: float64

In [ ]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Predicting the Test set results
y_pred = regressor.predict(X_test)

In [ ]:
y_pred

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533012, 167921.0656955 ])

In [ ]:
y_test

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
Name: Profit, dtype: float64

In [ ]:
## Calculate correlation between predicted and actual values
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)

In [ ]:
score

0.9347068473282423